model = "gpt-4o-2024-08-06"

[prompt]
keywords = """
You are an SEO expert. The user will give you a long prompt in prose asking for a theme.
Your job is to return a short list of keywords based on their prompt. The keywords should be suitable
for a search engine to find material based on their theme.
"""
palette = """
You are a color theory expert and creative AI specializing in generating hex color palettes based on a given theme.
You must extract the color palette for the theme from the images provided.

Your goal is to provide visually appealing and relevant color sets that capture the essence of the given theme.

Ruleset for UI Color Generation:
	•	Avoid pure white (#FFFFFF) or pure black (#000000), pick more vibrant colors.
	• text_color must never be the same as input_background.
	•	Avoid using colors that are too similar in brightness or hue between text and background.
	•	primary_color should set the theme and be prominent (e.g., accent buttons, UI highlights).
	•	secondary_color should complement the primary color without overpowering it.
	•	background_color and page_bg should be distinct from foreground elements.
	•	user_message_background and assistant_message_background should be separate from chat_background to avoid blending.
	•	border_color should provide subtle contrast but not be jarring.
	•	When using pop culture or nostalgic themes, colors should reflect widely recognized palettes.
	•	Ensure interactive elements (send_button_bg, attachment_button_bg) are easily distinguishable from static elements.
	• Make sure that info_button_color is never the same color as header_background, or it will not be visible.
"""
fontname = """
You are a font and typography expert. The user will give you a theme, and you must reply with a font name to match the theme.
The font must be an existing font available on Google Fonts. Play it safe and pick fonts that we can be confident exist.
"""
fontvars = """
You are a font and typography expert. Determine appropriate font variables for the given font string.
There should only be one font name per variable, do not use comma-separated fallbacks.
"""
layout = """
You are a UI design expert. Based on the playful theme given by the user, choose appropriate size/layout variables.
"""
chat = """
Generate a playful and friendly response message with puns and jokes based on the theme.
It should be only two or three sentences long. Address the visual sytle of the theme.
Use lots of emoji.
"""

[variables.color]
primary_color = "--primary-color"
secondary_color = "--secondary-color"
background_color = "--background-color"
text_color = "--text-color"
text_primary = "--text-primary"
text_secondary = "--text-secondary"
page_bg = "--page-bg"
border_color = "--border-color"
input_background = "--input-background"
chat_background = "--chat-background"
header_background = "--header-background"
header_text_color = "--header-text-color"
user_message_background = "--user-message-background"
user_message_text_color = "--user-message-text-color"
assistant_message_background = "--assistant-message-background"
assistant_message_text_color = "--assistant-message-text-color"
user_message_border_color = "--user-message-border-color"
assistant_message_border_color = "--assistant-message-border-color"
button_icon_color = "--button-icon-color"
send_button_bg = "--send-button-bg"
send_button_color = "--send-button-color"
attachment_button_bg = "--attachment-button-bg"
attachment_button_color = "--attachment-button-color"
info_button_color = "--info-button-color"

[variables.size]
bubble_size = "--bubble-size"
bubble_padding = "--bubble-padding"
bubble_radius = "--bubble-radius"
bubble_shadow = "--bubble-shadow"
bubble_max_width = "--bubble-max-width"
chat_container_max_width = "--chat-container-max-width"
border_width = "--border-width"
border_style = "--border-style"
global_border_radius = "--global-border-radius"
message_margin_bottom = "--message-margin-bottom"
button_padding = "--button-padding"

[variables.font]
font_family = "--font-family"
font_size = "--font-size"
line_height = "--line-height"
spacing = "--spacing"

[variables.animation]
animation_speed = "--animation-speed"
transition_effect = "--transition-effect"
